name: Build i Release aplikacji zakupowej

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux
            extension: ""
          - os: windows-latest
            label: win
            extension: ".exe"
          - os: macos-latest
            label: mac
            extension: ""

    steps:
    - name: Checkout kodu
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalacja zależności
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller reportlab

    - name: Budowanie aplikacji
      run: |
        pyinstaller --noconfirm --onefile --windowed main.spec

    - name: Przeniesienie pliku wykonywalnego z nazwą systemu
      run: |
        mkdir dist-artifacts
        cp dist/main dist-artifacts/ListaZakupow-${{ matrix.label }}${{ matrix.extension }}
      shell: bash

    - name: Upload artefaktów
      uses: actions/upload-artifact@v4
      with:
        name: ListaZakupow-${{ matrix.label }}
        path: dist-artifacts/*

    - name: Release i załączenie plików
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist-artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
